site_name: Noah123d
site_description: Building assemblies from STL models - A comprehensive STL to 3MF converter with grid layout capabilities
site_url: https://noah123d.readthedocs.io/
repo_url: https://github.com/42sol-eu/noah123d
repo_name: 42sol-eu/noah123d
edit_uri: edit/main/docs/

watch:
  - noah123d

nav:
  - Overview: "index.md"
  - Getting Started:
    - Installation: "getting-started/installation.md"
    - Quick Start: "getting-started/quickstart.md"
    - Basic Usage: "getting-started/basic-usage.md"
  - User Guide:
    - STL Conversion: "user-guide/stl-conversion.md"
    - Grid Layouts: "user-guide/grid-layouts.md"
    - 3MF Analysis: "user-guide/3mf-analysis.md"
    - Batch Processing: "user-guide/batch-processing.md"
  - API Reference:
    - Overview: "reference/index.md"
    - STLConverter: "reference/converters.md"
    - Archive3mf: "reference/archive3mf.md"
    - Model: "reference/model.md"
    - Directory: "reference/directory.md"
    - Analysis3MF: "reference/analyzer.md"
  - Examples:
    - Simple Conversion: "examples/simple-conversion.md"
    - Grid Layouts: "examples/grid-layouts.md"
    - Advanced Usage: "examples/advanced-usage.md"
    - Batch Processing: "examples/batch-processing.md"
  - Development:
    - Contributing: "development/contributing.md"
    - Architecture: "development/architecture.md"
    - Testing: "development/testing.md"
  - Changelog: "changelog.md"

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  logo: assets/logo.png
  favicon: assets/favicon.ico

extra_css:
  - assets/css/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - assets/js/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: 42sol-eu
      repo: noah123d
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            separate_signature: true
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
  - autorefs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/42sol-eu/noah123d
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/noah123d/
  version:
    provider: mike

copyright: |
  &copy; 2025 <a href="https://github.com/42sol-eu"  target="_blank" rel="noopener">42sol-eu</a>
